### ISSUE TITLE
112-medium-type-as-example discussion

### ISSUE THREAD

**Issue by madlabman** [kracekumar/python-typing-koans#18]
It look like this example has to be rewritten in the following manner (snippet is typed):
```python
# Annotate the resp_klass as the type of response class
# Documentation: https://docs.python.org/3/library/typing.html?highlight=typing#typing.Type
def make_response(data: JSONData, resp_klass: Type[JSONResponse] = JSONResponse) -> bytes:
    return resp_klass(data).make_response()
```
I guess that in this case the code has some meaning.
Also the is an unused import `Union` from `typing`.

**Comment by kracekumar** [comment]
Thank you, @madlabman, for reporting this. It's fixed in the commit https://github.com/kracekumar/python-typing-koans/commit/8a05722c166ec636bb41019c1a2ef9cc91403f50. I hope this fixes it.
